version: '3'
services:
  node:
    build:
      context: .
    image: regional-shipping-api
    ports:
        - "3000:3000"
    volumes:
        - .:/usr/src/app
    user: '1000'
    command: yarn run start
